### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Geek-Almighty** [hswayne77/xenserver_to_xen#4]
doesn't work anymore, prints out
```
xenmigrate 0.7.4 -- 2011.09.13
(c)2011 Jolokia Networks and Mark Pace -- jolokianetworks.com
```
after execution in ubuntu.

**Comment by kr105** [comment]
I had this same issue. Turns out I copy/pasted the example command line argument and modified only my filenames, this lead to accidentally using a weird unicode character instead of - (but it looked the same, for real), when i rewrote the entire command line by hand it started working. (I had to add a few debug lines to the code to find this, but whatever).

I hope it helps someone :)
